# Generated by Django 3.1 on 2020-08-07 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200807_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name_plural': 'cities1'},
        ),
    ]
